
# -----------------------------------------------------------------------------
# Console plugin list (for dein plugin manager)
# -----------------------------------------------------------------------------

# Highlight around cursor on big jump
[[plugins]]
repo = 'edluffy/specs.nvim'
hook_post_source = '''
highlight Specs guibg=#98c379 blend=50
lua <<EOF
require('specs').setup{
    show_jumps  = true,
    min_jump = 20,
    popup = {
        delay_ms = 0, -- delay before popup displays
        inc_ms = 10, -- time increments used for fade/resize effects
        blend = 60, -- starting blend, between 0-100 (fully transparent), see :h winblend
        width = 15,
        winhl = "Specs",
        fader = require('specs').pulse_fader,
        resizer = require('specs').shrink_resizer
    },
    ignore_filetypes = {},
    ignore_buftypes = {
        nofile = true,
    },
}
EOF
'''
