# -----------------------------------------------------------------------------
# Plugin list (for dein plugin manager)
# -----------------------------------------------------------------------------

# --------
# General
# --------

# Plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Start page
[[plugins]]
repo = 'mhinz/vim-startify'

# Auto change current dir
[[plugins]]
repo = 'airblade/vim-rooter'
hook_post_source = '''
let g:router_targets = '/,*'
let g:router_patterns = ['.git']
'''

# Close buffer keep window layout
[[plugins]]
repo = 'rbgrouleff/bclose.vim'

# Better window resizing
[[plugins]]
repo = 'simeji/winresizer'

# Cool status bar
[[plugins]]
repo = 'itchyny/lightline.vim'

# Tabline(buffer list on top) for lightline
[[plugins]]
repo = 'taohexxx/lightline-buffer'

# File type icon for lightline-buffer
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# File manager ranger in vim
[[plugins]]
repo =  'iberianpig/ranger-explorer.vim'

# Git TUI lazygit in vim
[[plugins]]
repo = 'kdheepak/lazygit.nvim'

# AST for vim
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

# Colorscheme gruvbox
[[plugins]]
repo = 'gruvbox-community/gruvbox'

# Indent visualizer
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# Depended by telescope
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# Popup window fizzy-finder
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

# Telescope Manage project
[[plugins]]
repo = 'nvim-telescope/telescope-project.nvim'

[[plugins]]
repo = "tpope/vim-fugitive"

# Git gutter icon
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add="""
let g:gitgutter_sign_added = '✚'
let g:gitgutter_sign_modified = '➜'
let g:gitgutter_sign_removed = '✘'
"""

# Never forget key binding
[[plugins]]
repo = 'folke/which-key.nvim'

# Undo with tree
[[plugins]]
repo = 'mbbill/undotree'

# ----
# lsp
# ----

# LSP integration with coc
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
git checkout release
'''
hook_add = '''
let g:coc_global_extensions = [
    \'coc-json',
    \'coc-lightbulb',
    \'coc-lua',
    \'coc-rust-analyzer',
    \'coc-texlab',
    \'coc-toml',
    \]
'''

# Telescope CoC integration
[[plugins]]
repo = 'fannheyward/telescope-coc.nvim'

# GitHub copilot
[[plugins]]
repo = 'github/copilot.vim'

